In [ ]:
# Temperature conversation from celsius to fahrenheit.
Temperature_in_Celsius = int(input("Enter the Temperature in celsius: "))
Temperature_in_Fahrenheit = (Temperature_in_Celsius * 9/5) + 32
print(f"Temperature in Fahrenheit: {Temperature_in_Fahrenheit}")

Enter the Temperature in celsius: 23
Temperature in Fahrenheit: 73.4


In [ ]:
# Temperature conversation from Fahrenheit to celsius.
Temperature_in_Fahrenheit = int(input("Enter the Temperature in fahrenheit: "))
Temperature_in_Celsius = ((Temperature_in_Fahrenheit - 32) * 5)/9
print(f"Temperature in Celsius: {Temperature_in_Celsius}")

Enter the Temperature in fahrenheit: 73
Temperature in Celsius: 22.77777777777778


In [ ]:
# Print the LCM of the two numbers.
import math

Number_1 = int(input("Enter first number: "))
Number_2 = int(input("Enter second number: "))

LCM = math.lcm(Number_1, Number_2)
print(f"LCM of {Number_1} and {Number_2} is {LCM}")

Enter first number: 12
Enter second number: 15
LCM of 12 and 15 is 60


In [ ]:
# Print the GCD of two numbers.
import math

Number_1 = int(input("Enter first number: "))
Number_2 = int(input("Enter second number: "))

GCD = math.gcd(Number_1, Number_2)
print(f"GCD of {Number_1} and {Number_2} is {GCD}")

Enter first number: 12
Enter second number: 16
GCD of 12 and 16 is 4


In [ ]:
# Print the number is a prime number or not.
def is_prime(number):
    if number <= 1:
        return False
    if number == 2:
        return True
    if number % 2 == 0:
        return False
    for i in range(3, int(number**0.5) + 1, 2):
        if number % i == 0:
            return False
    return True

try:
    number = int(input("Enter a number: "))
    if is_prime(number):
        print(f"{number} is a prime number")
    else:
        print(f"{number} is not a prime number")
except ValueError:
    print("Please enter a valid integer.")

Enter a number: 2
2 is a prime number


In [ ]:
# Print the matrix after doing Matrix multiplication.
import numpy as np

def matrix_multiplication(matrix1, matrix2):
    if matrix1.shape[1] != matrix2.shape[0]:
        raise ValueError("Number of columns in the first matrix must be equal to the number of rows in the second matrix.")
    return np.dot(matrix1, matrix2)

def main():
    matrix1 = np.array([[1, 2, 3], [4, 5, 6]])
    matrix3 = np.array([[1, 2], [3, 4], [5, 6]])

    try:
        result_multiplication = matrix_multiplication(matrix1, matrix3)
        print("Matrix Multiplication Result:")
        print(result_multiplication)
    except ValueError as e:
        print(f"Multiplication Error: {e}")

if __name__ == "__main__":
    main()

Matrix Multiplication Result:
[[22 28]
 [49 64]]


In [21]:
import numpy as np

def matrix_addition(matrix1, matrix2):
    if matrix1.shape != matrix2.shape:
        raise ValueError("Matrices must have the same dimensions for addition.")
    return matrix1 + matrix2

def main():
    matrix1 = np.array([[1, 2, 3], [4, 5, 6]])
    matrix2 = np.array([[7, 8, 9], [10, 11, 12]])

    try:
        result_addition = matrix_addition(matrix1, matrix2)
        print("Matrix Addition Result:")
        print(result_addition)
    except ValueError as e:
        print(f"Addition Error: {e}")

if __name__ == "__main__":
    main()

Matrix Addition Result:
[[ 8 10 12]
 [14 16 18]]
